### ISSUE TITLE
Bug in sum_even_fibonacci.py

### ISSUE THREAD

**Issue by AVokey** [atticuspatrick/InClass#5]
Description A clear and concise description of what the issue/bug is.
The sum of the even numbers does not increment past 0.

Steps to Reproduce

    First step to reproduce the issue/bug - Run the program
    Second step to reproduce the issue/bug
    Third step to reproduce the issue/bug

Expected Behavior A clear and concise description of what you expected to happen.
It is expected that the sum_even be 4613732 after running through a while loop to 4,000,000.

Actual Behavior A clear and concise description of what actually happened.
The sum_even variable does not increment past 0.

Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

    Operating System: Windows 10
    Browser: Firefox
    Version: 
    Any other relevant information

Possible Solution If you have any suggestions for a possible solution, please include them here.
The operator should be less than (<) not greater than (>).

Related Issues Are there any related issues? If so, please link to them here.

Priority How critical is this issue/bug? Low, medium, or high priority?
High priority.

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Always reproducible.

Impact What is the impact of this issue/bug? Low, medium, or high?
High impact. The answer will be completely wrong every time until this bug is fixed.

**Comment by hgsherid17** [comment]
Fixed issue in while loop
