### ISSUE TITLE
Bug in sum_even_fibonacci.cc

### ISSUE THREAD

**Issue by atticuspatrick** [atticuspatrick/InClass#6]
Description: Multiple syntax errors, > should be different on line 9, != should be different on line 10, and - should be different on line 14.

Steps to Reproduce

1.) Run the program

Expected Behavior 
Should sum all of the even Fibonacci numbers

Actual Behavior 
Subtracts the odd numbers in Fibonacci sequence.

Operating System: Windows
Browser: Chrome
Version: Windows 11
Possible Solution If you have any suggestions for a possible solution, please include them here.

greater than sign should be >= on line 9
!= should be == on line 10
minus sign should be + on line 14

Related Issues Are there any related issues? If so, please link to them here.
No related issues.

Priority How critical is this issue/bug? Low, medium, or high priority?
This is a critical bug as the file will not run properly if the syntax errors are not changed.

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
This bug can always be reproduced as it is a simple syntax error issue.

Impact What is the impact of this issue/bug? Low, medium, or high?
High impact as the file does not properly run without fixing the bug and is a simple fix.

**Comment by AVokey** [comment]
Fixed syntax errors identified in issue submission.
