### ISSUE TITLE
Issue in datetime_convert.cc

### ISSUE THREAD

**Issue by hgsherid17** [atticuspatrick/InClass#7]
Description 
Line 11: String date-str is not initialized with the selected date and time. Because of this, the program outputs an empty string instead of the expected output, which is a formatted string.

Steps to Reproduce
1. Remove the first line in main

Expected behavior
Expected program to output a formatted string that lists the date and time. The initial string should be stored in date_str, formatted with the pattern: "YYYY-MM-DD HH:MM:SS"

Actual Behavior
The program outputs an empty string

Additional Information

Operating System: MacOS
Browser: Chrome
Version: Monterey

Possible Solution
Store desired date and time in date_str string, formatted as YYYY-MM-DD HH:MM:SS
`date_str = 2022-03-17 10:45:30`

Priority
High

Reproducibility
This issue is reproduced every time the program is run

Impact
High impact - every modification after the first line is useless if the date-time string is not properly initialized

**Comment by anthonymazzola** [comment]
Fixed issue
